# Generated by Django 3.2.9 on 2021-12-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yourwishitems',
            field=models.ManyToManyField(default=None, related_name='favorites', to='user.Wish'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
